export enum Errors {
  PASSWORD_CONFIRMATION_INVALID = 'PASSWORD CONFIRMATION IS INVALID',
  INVALID_CREDENTIALS = 'INVALID CREDENTIALS',
  VALUE_REQUIRED = 'VALUE REQUIRED',
  NOTFOUND = 'NOTFOUND',
  INVALID_OPERATION = 'INVALID OPERATION',
  ALREADY_EXISTS = 'ALREADY EXISTS',
  ALREADY_ACTIVE = 'ALREADY ACTIVE',
  IS_NOT_MEMBER = 'IS NOT MEMBER',
  ALREADY_INACTIVE = 'ALREADY INACTIVE',
  HAS_NO_ROLE = 'HAS NO ROLE',
  NO_LONGER_MEMBER = 'NO LONGER MEMBER OF PROJECT',
}
